<a href="https://colab.research.google.com/github/mdjabedmollah/ml-learning/blob/main/Ml_four.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [69]:
documents = [ 'The␣canal␣is␣open␣to␣shipping.',
 'This␣is␣a␣ship␣shipping␣ship,␣shipping␣shipping␣ships.',
 'The␣ship␣locked␣into␣the␣new␣canal.' ]

print(documents)

['The␣canal␣is␣open␣to␣shipping.', 'This␣is␣a␣ship␣shipping␣ship,␣shipping␣shipping␣ships.', 'The␣ship␣locked␣into␣the␣new␣canal.']


In [70]:
lCasedocuments=[]
for  i in documents:
   lCasedocuments.append(i.lower())

print(lCasedocuments)

import string
punctuationRMove=[]
for i in lCasedocuments:
  punctuationRMove=["".join(j for j in i if j not in string.punctuation) for i in  lCasedocuments]
print(punctuationRMove)

['the␣canal␣is␣open␣to␣shipping.', 'this␣is␣a␣ship␣shipping␣ship,␣shipping␣shipping␣ships.', 'the␣ship␣locked␣into␣the␣new␣canal.']
['the␣canal␣is␣open␣to␣shipping', 'this␣is␣a␣ship␣shipping␣ship␣shipping␣shipping␣ships', 'the␣ship␣locked␣into␣the␣new␣canal']


In [71]:
prcDucuments=[]
for i in punctuationRMove:
  prcDucuments.append(i.split('~'))
print(prcDucuments)

[['the␣canal␣is␣open␣to␣shipping'], ['this␣is␣a␣ship␣shipping␣ship␣shipping␣shipping␣ships'], ['the␣ship␣locked␣into␣the␣new␣canal']]


In [72]:
from sklearn.feature_extraction.text import CountVectorizer

count_vector = CountVectorizer()

count_vector.fit(documents)
print(count_vector.get_feature_names_out())


['canal' 'into' 'is' 'locked' 'new' 'open' 'ship' 'shipping' 'ships' 'the'
 'this' 'to']


In [73]:
from collections import Counter
Frequnecy_list=[]
for i in prcDucuments:
   Frequnecy_count=Counter(i)
   Frequnecy_list.append(Frequnecy_count)

print (Frequnecy_list)



[Counter({'the␣canal␣is␣open␣to␣shipping': 1}), Counter({'this␣is␣a␣ship␣shipping␣ship␣shipping␣shipping␣ships': 1}), Counter({'the␣ship␣locked␣into␣the␣new␣canal': 1})]


In [74]:
docarray = count_vector.transform(documents ).toarray ( )
print(docarray)

[[1 0 1 0 0 1 0 1 0 1 0 1]
 [0 0 1 0 0 0 2 3 1 0 1 0]
 [1 1 0 1 1 0 1 0 0 2 0 0]]


In [75]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd


docarray = count_vector.fit_transform(documents).toarray()

frequency_matrix = pd.DataFrame(docarray, columns=count_vector.get_feature_names_out())

print(frequency_matrix)


   canal  into  is  locked  new  open  ship  shipping  ships  the  this  to
0      1     0   1       0    0     1     0         1      0    1     0   1
1      0     0   1       0    0     0     2         3      1    0     1   0
2      1     1   0       1    1     0     1         0      0    2     0   0


In [76]:
import pandas as pd

# Read the dataset with tab separator
df = pd.read_csv('https://raw.githubusercontent.com/mdjabedmollah/ml-learning/refs/heads/main/SMSSpamCollection', sep='\t', header=None, names=['label', 'message'])

# Display the first 5 rows
df.head()


label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [77]:
from sklearn.model_selection import train_test_split


X_train, X_test, y_train, y_test = train_test_split(
    df['message'], df['label'], random_state=1
)

print("Original dataset contains", df.shape[0], "messages")
print("Training set contains", X_train.shape[0], "messages")
print("Testing set contains", X_test.shape[0], "messages")


Original dataset contains 5572 messages
Training set contains 4179 messages
Testing set contains 1393 messages


In [78]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer

count_vector = CountVectorizer()

X_train_vectorized = count_vector.fit_transform(X_train)
naive_bayes = MultinomialNB()
naive_bayes.fit(X_train_vectorized, y_train)


MultinomialNB()

In [79]:
import numpy as np

predictions = naive_bayes.predict(X_test)

print(np.mean(predictions == y_test))



ValueError: could not convert string to float: 'Yep, by the pretty sculpture'